# Generated by Django 3.2.13 on 2022-07-04 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pesel',
            field=models.IntegerField(unique=True, verbose_name='PESEL (polish ID number)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(to='e_clinic_app.Procedure', verbose_name='Treatments performed by doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pwz',
            field=models.IntegerField(unique=True, verbose_name="PWZ (doctor's license"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(to='e_clinic_app.Specialization', verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title_or_degree',
            field=models.IntegerField(choices=[(1, 'lek.'), (2, 'lek. dent'), (3, 'dr n. med.'), (4, 'dr hab. n. med.'), (5, 'prof. dr hab. n. med.')], verbose_name='Scientific degree'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Office Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification_type',
            field=models.IntegerField(choices=[(1, 'ID card'), (2, 'Passport')], verbose_name='identification type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.IntegerField(unique=True, verbose_name='PESEL (polish ID number)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='treatment name'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='treatment price'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='specialization name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(verbose_name="Day's date"),
        ),
        migrations.AlterField(
            model_name='term',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='term',
            name='hour_from',
            field=models.TimeField(verbose_name='From hour'),
        ),
        migrations.AlterField(
            model_name='term',
            name='hour_to',
            field=models.TimeField(verbose_name='To hour'),
        ),
        migrations.AlterField(
            model_name='term',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.term', verbose_name='Visit term'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.procedure', verbose_name='Chosen treatment'),
        ),
    ]
