# Generated by Django 3.2.13 on 2022-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0002_delete_some'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='hour_from',
            field=models.TimeField(verbose_name='Od'),
        ),
        migrations.AlterField(
            model_name='term',
            name='hour_to',
            field=models.TimeField(verbose_name='Do'),
        ),
    ]
