# Generated by Django 3.2.14 on 2022-07-08 20:56

import django.core.validators
from django.db import migrations, models
import e_clinic_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0002_auto_20220704_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pesel',
            field=models.IntegerField(unique=True, validators=[e_clinic_app.validators.pesel_validator], verbose_name='PESEL (polish ID number)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pwz',
            field=models.IntegerField(unique=True, validators=[e_clinic_app.validators.pwz_validator], verbose_name="PWZ (doctor's license"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.IntegerField(unique=True, validators=[e_clinic_app.validators.pesel_validator], verbose_name='PESEL (polish ID number)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[e_clinic_app.validators.phone_regex_validator], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='treatment price'),
        ),
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(validators=[e_clinic_app.validators.date_validator], verbose_name="Day's date"),
        ),
    ]
