# Generated by Django 3.2.14 on 2022-07-08 21:02

from django.db import migrations, models
import e_clinic_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0003_auto_20220708_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pesel',
            field=models.CharField(max_length=11, unique=True, validators=[e_clinic_app.validators.pesel_validator], verbose_name='PESEL (polish ID number)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.CharField(max_length=11, unique=True, validators=[e_clinic_app.validators.pesel_validator], verbose_name='PESEL (polish ID number)'),
        ),
    ]
