# Generated by Django 3.2.13 on 2022-06-29 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_clinic_app', '0004_auto_20220629_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.IntegerField(unique=True, verbose_name='PESEL')),
                ('pwz', models.IntegerField(unique=True, verbose_name='PWZ')),
                ('title_or_degree', models.IntegerField(choices=[(1, 'lek.'), (2, 'lek. dent'), (3, 'dr n. med.'), (4, 'dr hab. n. med.'), (5, 'prof. dr hab. n. med.')], verbose_name='Tytuł zawodowy, stopień naukowy bądź tytuł naukowy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nr gabinetu')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.IntegerField(unique=True, verbose_name='PESEL')),
                ('identification_type', models.IntegerField(choices=[(1, 'Dowód tożsamości'), (2, 'Paszport'), (3, 'Akt urodzenia*')], verbose_name='dowód tożsamości')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='E-mail')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='Telefon komórkowy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nazwa Zabiegu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Koszt zabiegu')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Specjalizacja')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dzień')),
                ('hour_from', models.TimeField(verbose_name='Od')),
                ('hour_to', models.TimeField(verbose_name='Do')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.office', verbose_name='Gabinet')),
            ],
            options={
                'unique_together': {('date', 'hour_from', 'hour_to', 'office')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ManyToManyField(to='e_clinic_app.Term', verbose_name='Data wizyty')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.doctor', verbose_name='Lekarz')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.patient', verbose_name='Pacjent')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.procedure', verbose_name='Wybrany zabieg')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(to='e_clinic_app.Procedure', verbose_name='Zabiegi wykonywane przez lekarza'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(to='e_clinic_app.Specialization', verbose_name='Specjalizacja'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='terms',
            field=models.ManyToManyField(to='e_clinic_app.Term', verbose_name='Dostępność'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
