# Generated by Django 3.2.13 on 2022-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0005_auto_20220629_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='term',
            name='office',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
