# Generated by Django 3.2.13 on 2022-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0007_auto_20220629_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.ManyToManyField(to='e_clinic_app.Term', verbose_name='Termin wizyty'),
        ),
    ]
