# Generated by Django 3.2.13 on 2022-06-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0008_auto_20220629_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='e_clinic_app.term', verbose_name='Termin wizyty'),
            preserve_default=False,
        ),
    ]
