# Generated by Django 3.2.13 on 2022-06-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_clinic_app', '0009_auto_20220629_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
